/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CoursePaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "coursePrices"
      | "enrollments"
      | "getEthAmount"
      | "getLatestPrice"
      | "isEnrolled"
      | "owner"
      | "priceFeed"
      | "purchaseCourse"
      | "setCoursePrice"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CoursePurchased"): EventFragment;

  encodeFunctionData(
    functionFragment: "coursePrices",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "enrollments",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isEnrolled",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoursePrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "coursePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enrollments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEnrolled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoursePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    courseId: string,
    usdPrice: BigNumberish,
    ethPaid: BigNumberish,
    ethUsdPrice: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    courseId: string,
    usdPrice: bigint,
    ethPaid: bigint,
    ethUsdPrice: bigint
  ];
  export interface OutputObject {
    buyer: string;
    courseId: string;
    usdPrice: bigint;
    ethPaid: bigint;
    ethUsdPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoursePayment extends BaseContract {
  connect(runner?: ContractRunner | null): CoursePayment;
  waitForDeployment(): Promise<this>;

  interface: CoursePaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  coursePrices: TypedContractMethod<[arg0: string], [bigint], "view">;

  enrollments: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  getEthAmount: TypedContractMethod<[usdCents: BigNumberish], [bigint], "view">;

  getLatestPrice: TypedContractMethod<[], [bigint], "view">;

  isEnrolled: TypedContractMethod<
    [user: AddressLike, courseId: string],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceFeed: TypedContractMethod<[], [string], "view">;

  purchaseCourse: TypedContractMethod<[courseId: string], [void], "payable">;

  setCoursePrice: TypedContractMethod<
    [courseId: string, usdCents: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "coursePrices"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "enrollments"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEthAmount"
  ): TypedContractMethod<[usdCents: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEnrolled"
  ): TypedContractMethod<
    [user: AddressLike, courseId: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[courseId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "setCoursePrice"
  ): TypedContractMethod<
    [courseId: string, usdCents: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;

  filters: {
    "CoursePurchased(address,string,uint256,uint256,int256)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
  };
}
